apiVersion: 1

datasources:
  - name: TimescaleDB
    type: postgres
    url: timescaledb:5432
    user: $POSTGRES_USER
    secureJsonData:
      password: $POSTGRES_PASSWORD
    jsonData:
      database: $POSTGRES_DB
      sslmode: disable
      maxOpenConns: 10
      maxIdleConns: 10
      timescaledb: true
    isDefault: true
    editable: true
